QQmlModel: QQmlModelVersion Class Reference
QQmlModelVersion Class Reference
Static Public Member Functions
static uint32_t GetMajor ()
static uint32_t GetMinor ()
static uint32_t GetPatch ()
static uint32_t GetTag ()
static QString GetVersion ()
Member Function Documentation
GetMajor()
uint32_t QQmlModelVersion::GetMajor () static
Library Major Version
Referenced by GetVersion().
GetMinor()
uint32_t QQmlModelVersion::GetMinor () static
Library Minor Version
Referenced by GetVersion().
GetPatch()
uint32_t QQmlModelVersion::GetPatch () static
Library Patch Version
GetTag()
uint32_t QQmlModelVersion::GetTag () static
Library Tag Version
Referenced by GetVersion().
GetVersion()
QString QQmlModelVersion::GetVersion () static
Get version in form major.minor.patch.tag
References GetMajor(), GetMinor(), and GetTag().
The documentation for this class was generated from the following files:
QQmlModelShared.h
QQmlModelShared.cpp